In [4]:
import pandas as pd
data=pd.read_excel("Pandas(5).xlsx")
data

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [5]:
#1.Display the first 10 rows using iloc.
data.iloc[0:10]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.0523,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.4453,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.3665,12,6362.85,90193
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.2600,18,113.25,90197
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.4673,16,1515.17,90194

In [6]:
#2.display the last 5 rows using iloc.
data.iloc[-5:]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [7]:
#3.display rows 20 to 30 and all columns.
data.iloc[20:31]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
20,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-24.0300,7,22.23,86838
21,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-37.0300,4,13.99,86838
22,24848,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-0.7100,4,14.26,86838
23,24845,Medium,0.01,6.48,7.86,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2013-05-12,2013-05-13,-44.5400,4,29.55,86845
24,18181,Critical,0.00,4.42,4.99,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2010-04-08,2010-04-09,-59.8200,7,33.47,86837
25,20925,Medium,0.01,35.94,6.66,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2010-05-28,2010-05-28,261.8757,10,379.53,86839
26,18263,Medium,0.03,1.76,0.70,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2011-12-04,2011-12-06,-1.1700,10,17.39,86840
27,18554,Medium,0.04,5.98,5.20,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2012-04-29,2012-05-01,-24.0300,3,19.04,86841
28,22781,Low,0.00,7.59,4.00,15,Timothy Reese,Regular Air,Small Business,Furniture,...,East,New York,Smithtown,11787,2013-01-19,2013-01-21,23.2668,4,33.72,86842
29,23287,Low,0.07,4.13,6.89,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2013-01-21,2013-01-23,-174.2696,9,38.18,86843
30,26267,High,0.04,2.98,1.58,16,Sarah Ramsey,Regular Air,Small Business,Office Supplies,...,East,New York,Syracuse,13210,2010-02-12,2010-02-15,2.6300,6,18.80,86836

In [8]:
#4.Display the first 5 rows with only customer Name, Region, and Sales columns using iloc.
# print(data.columns)
# data.loc[:4,['Customer Name', 'Region','sales']]
data.iloc[:5,[6,14,22]]

     Customer Name   Region    Sales
0  Janice Fletcher  Central     5.90
1    Bonnie Potter     West    13.01
2    Bonnie Potter     West    49.92
3    Bonnie Potter     West    41.64
4    Bonnie Potter     West  1446.67

In [9]:
# 5. display rows 50 to 60 with columns product category to sales using iloc.
# data.coumns
data.iloc[50:61,10:23]

,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales
50,Appliances,Small Box,Hoover Commercial Soft Guard Upright Vacuum An...,0.58,East,New York,New York City,10012,2012-04-06,2012-04-08,-96.33000,18,156.38
51,Appliances,Small Box,Belkin F9M820V08 8 Outlet Surge,0.56,East,New York,New York City,10012,2012-05-15,2012-05-16,461.65000,60,2585.97
52,Binders and Binder Accessories,Small Box,"Fellowes Twister Kit, Gray/Clear, 3/pkg",0.40,East,New York,New York City,10012,2012-05-15,2012-05-15,-117.10450,36,303.40
53,Storage & Organization,Large Box,Space Solutions Commercial Steel Shelving,0.80,East,New York,New York City,10012,2012-05-31,2012-06-02,-929.68000,50,3085.41
54,Tables,Jumbo Box,Anderson Hickey Conga Table Tops & Accessories,0.76,East,New York,New York City,10012,2012-05-31,2012-06-01,-53.78400,5,122.40
55,Chairs & Chairmats,Jumbo Drum,Office Star Flex Back Scooter Chair with White...,0.71,East,New York,New York City,10012,2013-10-02,2013-10-04,126.31000,88,10303.73
56,Labels,Small Box,Avery 485,0.38,East,New York,New York City,10012,2013-10-02,2013-10-04,223.38000,67,872.68
57,Office Furnishings,Small Pack,Nu-Dell Leatherette Frames,0.49,West,California,Laguna Hills,92653,2011-11-11,2011-11-12,284.52600,36,519.23
58,Paper,Small Box,Xerox 1979,0.40,West,California,Laguna Hills,92653,2011-11-11,2011-11-12,859.26390,37,1245.31
59,Paper,Small Box,Xerox 1929,0.39,West,California,Laguna Hills,92653,2012-09-10,2012-09-13,83.24000,7,165.11
60,Tables,Jumbo Box,BPI Conference Tables,0.71,West,California,Laguna Hills,92653,2013-11-18,2013-11-25,353.77216,11,1591.71

In [10]:
# 6.display every 5th row from the dataset using iloc.
data.iloc[::5]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
10,24563,Critical,0.07,6.48,6.60,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,-13.860000,4,28.61,90200
15,20877,Medium,0.10,286.85,61.76,9,Lorraine Houston,Delivery Truck,Home Office,Furniture,...,East,New Jersey,Camden,8101,2012-12-25,2012-12-27,-346.615198,8,1794.27,90199
20,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-24.030000,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9405,21952,Not Specified,0.05,10.91,2.99,3397,Andrea Shaw,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Danville,61832,2013-07-09,2013-07-11,-11.673144,1,12.48,87547
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.912300,29,1705.67,87551
9415,26043,Not Specified,0.06,30.98,6.50,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2012-07-04,2012-07-07,-113.600000,3,96.79,87540
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [11]:
#7.display the last 10 rows and only the last 4 columns using iloc.
data.iloc[-10:,-4:]

           Profit  Quantity ordered new    Sales  Order ID
9416     3.312000                     8    67.50     87545
9417   606.309900                     8   878.71     87546
9418   -15.030000                     1    43.90     87546
9419   411.481500                    19   596.35     87549
9420  -513.790420                    10  1969.31     87531
9421   137.860000                    13   447.87     87532
9422   -39.070000                     3    13.23     87532
9423 -1225.029097                     4  2215.93     87533
9424   349.485000                     5   506.50     87530
9425    78.062400                    23   172.48     87533

In [12]:
#loc
#1.display rows 0 to 10 using loc.
data.loc[0:10]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.0523,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.4453,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.3665,12,6362.85,90193
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.2600,18,113.25,90197
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.4673,16,1515.17,90194
10,24563,Critical,0.07,6.48,6.60,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,-13.8600,4,28.61,90200

In [13]:
#2.display only the customer name and sales columns using loc.
data.loc[:,["Customer Name","Sales"]]

        Customer Name    Sales
0     Janice Fletcher     5.90
1       Bonnie Potter    13.01
2       Bonnie Potter    49.92
3       Bonnie Potter    41.64
4       Bonnie Potter  1446.67
...               ...      ...
9421   Frederick Cole   447.87
9422   Frederick Cole    13.23
9423   Frederick Cole  2215.93
9424    Tammy Buckley   506.50
9425    Tammy Buckley   172.48

[9426 rows x 2 columns]

In [15]:
#3.display rows 100 to 110 with columns.Region,State or Province, and sales.
# data.columns
data.loc[100:110,["Region","State or Province","Sales"]]

      Region State or Province    Sales
100     West            Oregon    62.59
101  Central          Illinois    17.12
102  Central          Illinois    90.80
103  Central          Illinois   113.59
104     West        Washington    30.96
105     West        Washington   299.74
106     West        Washington   291.56
107     West        Washington   158.27
108     West        Washington   647.07
109     West        Washington    83.01
110     West        Washington  1396.96

In [16]:
#4.display rows 20 to 30 and all columns using loc.
data.loc[20:30]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
20,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-24.0300,7,22.23,86838
21,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-37.0300,4,13.99,86838
22,24848,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-0.7100,4,14.26,86838
23,24845,Medium,0.01,6.48,7.86,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2013-05-12,2013-05-13,-44.5400,4,29.55,86845
24,18181,Critical,0.00,4.42,4.99,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2010-04-08,2010-04-09,-59.8200,7,33.47,86837
25,20925,Medium,0.01,35.94,6.66,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2010-05-28,2010-05-28,261.8757,10,379.53,86839
26,18263,Medium,0.03,1.76,0.70,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2011-12-04,2011-12-06,-1.1700,10,17.39,86840
27,18554,Medium,0.04,5.98,5.20,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2012-04-29,2012-05-01,-24.0300,3,19.04,86841
28,22781,Low,0.00,7.59,4.00,15,Timothy Reese,Regular Air,Small Business,Furniture,...,East,New York,Smithtown,11787,2013-01-19,2013-01-21,23.2668,4,33.72,86842
29,23287,Low,0.07,4.13,6.89,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,2013-01-21,2013-01-23,-174.2696,9,38.18,86843
30,26267,High,0.04,2.98,1.58,16,Sarah Ramsey,Regular Air,Small Business,Office Supplies,...,East,New York,Syracuse,13210,2010-02-12,2010-02-15,2.6300,6,18.80,86836

In [18]:
#5.display rows 0 to 5 with columns customer name,city, and profit.
data.loc[0:5],["Customer Name","City","Profit"]

(   Row ID Order Priority  Discount  Unit Price  Shipping Cost  Customer ID  \
 0   18606  Not Specified      0.01        2.88           0.50            2
 1   20847           High      0.01        2.84           0.93            3
 2   23086  Not Specified      0.03        6.68           6.15            3
 3   23087  Not Specified      0.01        5.68           3.60            3
 4   23088  Not Specified      0.00      205.99           2.50            3
 5   23597         Medium      0.09       55.48          14.30            3

      Customer Name    Ship Mode Customer Segment Product Category  ...  \
 0  Janice Fletcher  Regular Air        Corporate  Office Supplies  ...
 1    Bonnie Potter  Express Air        Corporate  Office Supplies  ...
 2    Bonnie Potter  Express Air        Corporate  Office Supplies  ...
 3    Bonnie Potter  Regular Air        Corporate  Office Supplies  ...
 4    Bonnie Potter  Express Air        Corporate       Technology  ...
 5    Bonnie Potter  Express Air        Corporate  Office Supplies  ...

     Region State or Province       City  Postal Code Order Date  Ship Date  \
 0  Central          Illinois    Addison        60101 2012-05-28 2012-05-30
 1     West        Washington  Anacortes        98221 2010-07-07 2010-07-08
 2     West        Washington  Anacortes        98221 2011-07-27 2011-07-28
 3     West        Washington  Anacortes        98221 2011-07-27 2011-07-28
 4     West        Washington  Anacortes        98221 2011-07-27 2011-07-27
 5     West        Washington  Anacortes        98221 2011-11-09 2011-11-11

       Profit  Quantity ordered new    Sales Order ID
 0     1.3200                     2     5.90    88525
 1     4.5600                     4    13.01    88522
 2   -47.6400                     7    49.92    88523
 3   -30.5100                     7    41.64    88523
 4   998.2023                     8  1446.67    88523
 5  1388.0523                    37  2011.67    88524

 [6 rows x 24 columns],
 ['Customer Name', 'City', 'Profit'])

In [19]:
#6.Display only the columns from Customer name to sales using loc.
data.loc[:,["Customer Name","Sales"]]

        Customer Name    Sales
0     Janice Fletcher     5.90
1       Bonnie Potter    13.01
2       Bonnie Potter    49.92
3       Bonnie Potter    41.64
4       Bonnie Potter  1446.67
...               ...      ...
9421   Frederick Cole   447.87
9422   Frederick Cole    13.23
9423   Frederick Cole  2215.93
9424    Tammy Buckley   506.50
9425    Tammy Buckley   172.48

[9426 rows x 2 columns]

In [20]:
#7.Display the first 15 rows with columns order priority, ship mode, and profit.
data.loc[0:15,["Order Priority","Ship Mode","Profit"]]

   Order Priority       Ship Mode       Profit
0   Not Specified     Regular Air     1.320000
1            High     Express Air     4.560000
2   Not Specified     Express Air   -47.640000
3   Not Specified     Regular Air   -30.510000
4   Not Specified     Express Air   998.202300
5          Medium     Express Air  1388.052300
6             Low  Delivery Truck  1001.445300
7   Not Specified  Delivery Truck  4390.366500
8             Low     Regular Air  -141.260000
9            High     Regular Air  1045.467300
10       Critical     Regular Air   -13.860000
11       Critical     Regular Air    57.580500
12       Critical     Regular Air  1176.505200
13           High     Regular Air    72.992800
14         Medium  Delivery Truck  -158.740000
15         Medium  Delivery Truck  -346.615198

In [21]:
# filtering with masking
#1.display all record where sales>500.
data.loc[data["Sales"]>500]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.467300,16,1515.17,90194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9417,23413,Critical,0.07,115.79,1.99,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2013-04-27,2013-04-29,606.309900,8,878.71,87546
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,...,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.481500,19,596.35,87549
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

In [23]:
#2.display all products where profit<0.
data.loc[data["Profit"]<0]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.260000,18,113.25,90197
10,24563,Critical,0.07,6.48,6.60,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,-13.860000,4,28.61,90200
14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,...,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9415,26043,Not Specified,0.06,30.98,6.50,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2012-07-04,2012-07-07,-113.600000,3,96.79,87540
9418,23414,Critical,0.02,37.44,4.27,3400,Florence Gold,Regular Air,Corporate,Office Supplies,...,East,West Virginia,Fairmont,26554,2013-04-27,2013-04-30,-15.030000,1,43.90,87546
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533

In [24]:
#3.display customers from the west region.
data.loc[data["Region"]=="West"]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9390,23658,Medium,0.00,12.28,4.86,3394,Julia Padgett,Express Air,Consumer,Office Supplies,...,West,Washington,Puyallup,98373,2012-03-10,2012-03-11,115.216200,13,166.98,87911
9391,22578,Not Specified,0.04,6.84,8.37,3394,Julia Padgett,Regular Air,Consumer,Office Supplies,...,West,Washington,Puyallup,98373,2013-08-19,2013-08-20,-117.252960,24,161.87,87913
9392,22579,Not Specified,0.07,125.99,7.69,3394,Julia Padgett,Regular Air,Consumer,Technology,...,West,Washington,Puyallup,98373,2013-08-19,2013-08-20,139.258512,10,995.95,87913
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [25]:
#4.display records where discount>0.05.
data.loc[data["Discount"]>0.05]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.260000,18,113.25,90197
10,24563,Critical,0.07,6.48,6.60,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,-13.860000,4,28.61,90200
12,24565,Critical,0.10,85.99,0.99,6,Dwight Hwang,Regular Air,Home Office,Technology,...,West,California,San Jose,95123,2012-12-29,2012-12-31,1176.505200,24,1705.08,90200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [30]:
#5.display products whose quantity ordered new>10.
data.loc[data["Quantity ordered new"]>10]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.0523,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.4453,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.3665,12,6362.85,90193
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.2600,18,113.25,90197
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.4673,16,1515.17,90194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9413,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554,2010-10-04,2010-10-04,-24.7104,15,135.78,87537
9414,26042,Not Specified,0.09,8.46,3.62,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2012-07-04,2012-07-04,-60.4000,13,105.29,87540
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,...,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.4815,19,596.35,87549
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.8600,13,447.87,87532
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.0624,23,172.48,87533

In [31]:
#6.display orders where Shipping Cost>20.
data.loc[data["Shipping Cost"]>20]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,...,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
15,20877,Medium,0.10,286.85,61.76,9,Lorraine Houston,Delivery Truck,Home Office,Furniture,...,East,New Jersey,Camden,8101,2012-12-25,2012-12-27,-346.615198,8,1794.27,90199
39,20578,Low,0.02,110.98,30.00,18,Laurie Hanna,Delivery Truck,Small Business,Furniture,...,West,Montana,Helena,59601,2013-10-02,2013-10-04,126.310000,22,2575.93,90039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9393,18988,Low,0.02,276.20,24.49,3396,Stuart Wiley,Regular Air,Corporate,Furniture,...,Central,Illinois,Crystal Lake,60014,2012-08-07,2012-08-11,2206.689000,11,3198.10,87541
9394,19370,High,0.00,140.98,53.48,3396,Stuart Wiley,Delivery Truck,Corporate,Furniture,...,Central,Illinois,Crystal Lake,60014,2012-08-16,2012-08-17,-140.727600,16,2327.54,87542
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,...,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.426000,41,7158.10,87544
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533

In [32]:
#7.display records where product category is furniture
data.loc[data["Product Category"]=="Furniture"]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,...,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
15,20877,Medium,0.10,286.85,61.76,9,Lorraine Houston,Delivery Truck,Home Office,Furniture,...,East,New Jersey,Camden,8101,2012-12-25,2012-12-27,-346.615198,8,1794.27,90199
17,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,2010-08-15,2010-08-17,-53.809600,22,211.15,90192
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.470500,16,1164.45,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,...,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.426000,41,7158.10,87544
9413,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554,2010-10-04,2010-10-04,-24.710400,15,135.78,87537
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

In [33]:
# values_count()
#1.count the number of orders in each region.
data["Region"].value_counts().sort_values()

Region
South      1954
West       2284
East       2289
Central    2899
Name: count, dtype: int64

In [35]:
#2.count the number of customers in each Customer Segment.
data["Customer Segment"].value_counts()

Customer Segment
Corporate         3375
Home Office       2316
Consumer          1894
Small Business    1841
Name: count, dtype: int64

In [36]:
#3.count the number of products in each Product Category.
data["Product Category"].value_counts()

Product Category
Office Supplies    5181
Technology         2312
Furniture          1933
Name: count, dtype: int64

In [37]:
#4.count the number of orders by Ship Mode.
data["Ship Mode"].value_counts()

Ship Mode
Regular Air       7036
Delivery Truck    1283
Express Air       1107
Name: count, dtype: int64

In [38]:
#5.count the number of products in each Product Sub-Category.
data["Product Sub-Category"].value_counts()

Product Sub-Category
Paper                             1379
Binders and Binder Accessories    1028
Telephones and Communication       992
Office Furnishings                 883
Computer Peripherals               846
Pens & Art Supplies                721
Storage & Organization             610
Appliances                         492
Chairs & Chairmats                 440
Tables                             404
Office Machines                    376
Labels                             329
Envelopes                          272
Bookcases                          206
Rubber Bands                       195
Scissors, Rulers and Trimmers      155
Copiers and Fax                     98
Name: count, dtype: int64

In [39]:
#6.count the number of orders in each Order Priority.
data["Order Priority"].value_counts()

Order Priority
High             1970
Low              1926
Not Specified    1881
Medium           1844
Critical         1804
Critical            1
Name: count, dtype: int64

In [40]:
#7.count the number of records for each State or Province.
data["State or Province"].value_counts()

State or Province
California              1021
Texas                    646
Illinois                 584
New York                 574
Florida                  522
Ohio                     396
Washington               327
Michigan                 327
Pennsylvania             271
North Carolina           251
Indiana                  241
Minnesota                239
Massachusetts            222
Georgia                  214
Virginia                 198
Maryland                 178
Colorado                 177
New Jersey               177
Wisconsin                169
Oregon                   168
Tennessee                166
Missouri                 161
Iowa                     156
Utah                     146
Arizona                  134
Kansas                   133
Maine                    128
Alabama                  125
Arkansas                 123
Idaho                    114
South Carolina           105
Oklahoma                 104
Louisiana                 89
New Mexico                84
Kentucky                  83
Connecticut               82
Mississippi               78
Nebraska                  77
District of Columbia      68
Vermont                   61
New Hampshire             54
Montana                   49
West Virginia             43
Nevada                    43
North Dakota              34
South Dakota              28
Wyoming                   21
Rhode Island              20
Delaware                  15
Name: count, dtype: int64

In [43]:
# sort_values()
#1.sort the dataset by Sales in ascending order.
data["Sales"].sort_values()

4369         1.32
932          1.62
2770         1.65
7511         2.24
62           2.25
          ...
1418     43046.20
4642     45737.33
7040     48418.58
7013     50332.66
8461    100119.16
Name: Sales, Length: 9426, dtype: float64

In [44]:
#2.Sort the dataset by Sales in discending order.
data["Sales"].sort_values(ascending=False)

8461    100119.16
7013     50332.66
7040     48418.58
4642     45737.33
1418     43046.20
          ...
1066         2.25
7511         2.24
2770         1.65
932          1.62
4369         1.32
Name: Sales, Length: 9426, dtype: float64

In [45]:
#3.sort the dataset by Porfit from highest to lowest.
data["Profit"].sort_values(ascending=False)

9132    16332.414000
4189    12504.904500
9404    11429.477400
4642     9228.225600
859      9195.975000
            ...
5402   -13562.637408
4844   -13706.464000
7800   -14140.701600
4338   -14369.123580
4659   -16476.838000
Name: Profit, Length: 9426, dtype: float64

In [46]:
#4.sort the dataset by Customer Name alphabetically.
data["Customer Name"].sort_values()

8946    Aaron Davies Bruce
8945    Aaron Davies Bruce
8943    Aaron Davies Bruce
8944    Aaron Davies Bruce
4323             Aaron Day
               ...
3419        Zachary Potter
3418        Zachary Potter
3420        Zachary Potter
1316            Zachary Wu
2073            Zachary Yu
Name: Customer Name, Length: 9426, dtype: object

In [47]:
#5.sort the dataset by Region and then Sales.
data["Region"].sort_values()

0       Central
4406    Central
4407    Central
4408    Central
4409    Central
         ...
4630       West
4629       West
4628       West
7523       West
9425       West
Name: Region, Length: 9426, dtype: object

In [48]:
data["Sales"].sort_values()

4369         1.32
932          1.62
2770         1.65
7511         2.24
62           2.25
          ...
1418     43046.20
4642     45737.33
7040     48418.58
7013     50332.66
8461    100119.16
Name: Sales, Length: 9426, dtype: float64

In [49]:
#6.sort the dataset by Discount in descending order.
data["Discount"].sort_values(ascending=False)

8649    0.25
8661    0.21
5991    0.17
6000    0.16
5990    0.11
        ...
3749    0.00
1109    0.00
7329    0.00
7334    0.00
2582    0.00
Name: Discount, Length: 9426, dtype: float64

In [50]:
#7.sort the dataset by Order Date from oldest to newest.
data["Order Date"].sort_values

<bound method Series.sort_values of 0      2012-05-28
1      2010-07-07
2      2011-07-27
3      2011-07-27
4      2011-07-27
          ...
9421   2013-05-14
9422   2013-05-14
9423   2013-09-12
9424   2010-02-08
9425   2013-09-12
Name: Order Date, Length: 9426, dtype: datetime64[ns]>

In [54]:
# AND(&)
#1.Display records where Sales>500 and Profit>100.
import pandas as pd
data=pd.read_excel("Pandas(5).xlsx")
    
data[(data['Sales']>500)&(data['Profit']>100)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.0523,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.4453,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.3665,12,6362.85,90193
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.4673,16,1515.17,90194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,...,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.4260,41,7158.10,87544
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.9123,29,1705.67,87551
9417,23413,Critical,0.07,115.79,1.99,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2013-04-27,2013-04-29,606.3099,8,878.71,87546
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,...,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.4815,19,596.35,87549
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.4850,5,506.50,87530

In [55]:
#2.Dispaly customers from the West region and Furniture category.
data[(data["Region"]=="West") & (data["Product Category"]=="Furniture")]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.36650,12,6362.85,90193
35,23890,High,0.05,26.48,6.93,18,Laurie Hanna,Regular Air,Small Business,Furniture,...,West,Montana,Helena,59601,2010-05-15,2010-05-16,314.48130,17,455.77,90031
39,20578,Low,0.02,110.98,30.00,18,Laurie Hanna,Delivery Truck,Small Business,Furniture,...,West,Montana,Helena,59601,2013-10-02,2013-10-04,126.31000,22,2575.93,90039
57,19249,High,0.05,14.34,5.00,23,Lynn Moss,Regular Air,Corporate,Furniture,...,West,California,Laguna Hills,92653,2011-11-11,2011-11-12,284.52600,36,519.23,87655
60,18478,Low,0.10,146.05,80.20,23,Lynn Moss,Delivery Truck,Corporate,Furniture,...,West,California,Laguna Hills,92653,2013-11-18,2013-11-25,353.77216,11,1591.71,87669
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9254,25880,Medium,0.08,29.18,8.55,3352,Jason Hill,Express Air,Small Business,Furniture,...,West,Washington,Pullman,99163,2011-01-11,2011-01-12,224.91930,12,325.97,91299
9259,22914,Not Specified,0.01,18.65,3.77,3354,Sara Faulkner,Regular Air,Corporate,Furniture,...,West,California,Calexico,92231,2011-08-02,2011-08-04,41.62770,3,60.33,88593
9270,18629,Medium,0.03,160.98,30.00,3356,Richard Tan,Delivery Truck,Corporate,Furniture,...,West,Idaho,Eagle,83616,2010-05-04,2010-05-05,1304.90000,18,2934.16,88588
9386,18429,High,0.03,160.98,30.00,3393,Irene Murphy,Delivery Truck,Consumer,Furniture,...,West,Washington,Pullman,99163,2012-08-21,2012-08-23,836.70320,11,1852.24,87912
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.48500,5,506.50,87530

In [56]:
#3.display records where Discount>0.05 and Shipping Cost>20.
data[(data["Discount"]>0.05) & (data["Shipping Cost"])]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.260000,18,113.25,90197
10,24563,Critical,0.07,6.48,6.60,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,-13.860000,4,28.61,90200
12,24565,Critical,0.10,85.99,0.99,6,Dwight Hwang,Regular Air,Home Office,Technology,...,West,California,San Jose,95123,2012-12-29,2012-12-31,1176.505200,24,1705.08,90200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [57]:
#4.display orders where Quantity ordered new>10 and Profit>50.
data[(data["Quantity ordered new"]>10) & (data["Profit"]>50)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.0523,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.4453,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.3665,12,6362.85,90193
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.4673,16,1515.17,90194
11,24564,Critical,0.01,4.84,0.71,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,57.5805,17,83.45,90200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.9123,29,1705.67,87551
9411,26074,Critical,0.05,4.13,0.50,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,117.2655,40,169.95,87551
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,...,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.4815,19,596.35,87549
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.8600,13,447.87,87532
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.0624,23,172.48,87533

In [58]:
#5.display products where Product Category=Office Supplies and Sales>1000.
data[(data["Product Category"]=="Office Supplies")&(data["Sales"]>1000)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.05230,37,2011.67,88524
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.46730,16,1515.17,90194
51,3763,Critical,0.08,42.98,4.62,21,Tony Wilkins Winters,Express Air,Small Business,Office Supplies,...,East,New York,New York City,10012,2012-05-15,2012-05-16,461.65000,60,2585.97,26887
53,7082,Not Specified,0.06,64.65,35.00,21,Tony Wilkins Winters,Express Air,Small Business,Office Supplies,...,East,New York,New York City,10012,2012-05-31,2012-06-02,-929.68000,50,3085.41,50533
58,19250,High,0.00,30.98,8.74,23,Lynn Moss,Regular Air,Corporate,Office Supplies,...,West,California,Laguna Hills,92653,2011-11-11,2011-11-12,859.26390,37,1245.31,87655
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9377,23192,Critical,0.04,167.27,35.00,3386,Carmen Elmore,Regular Air,Corporate,Office Supplies,...,East,Ohio,Bowling Green,43402,2013-11-03,2013-11-03,253.79872,19,3174.20,88751
9400,20624,Low,0.00,1270.99,19.99,3397,Andrea Shaw,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Danville,61832,2010-06-07,2010-06-09,6384.43890,7,9252.81,87535
9404,22193,High,0.05,387.99,19.99,3397,Andrea Shaw,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Danville,61832,2012-11-25,2012-11-26,11429.47740,42,16564.46,87544
9406,22599,Critical,0.01,177.98,0.99,3398,Marc McDaniel,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Decatur,62521,2011-05-07,2011-05-09,902.10600,7,1307.40,87538
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.91230,29,1705.67,87551

In [59]:
#6.display records where Region=Central and Profit<0.
data[(data["Region"]=="Central")&(data["Profit"]>0)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32000,2,5.90,88525
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.47050,16,1164.45,86838
102,20936,Medium,0.10,7.08,2.35,39,Ian L O'Donnell,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Alton,62002,2011-07-03,2011-07-05,23.82000,14,90.80,88682
111,23651,Medium,0.10,39.48,3.99,45,Melinda Sloan,Regular Air,Home Office,Office Supplies,...,Central,Texas,Coppell,75019,2012-02-24,2012-02-26,338.62440,13,490.76,91578
116,19337,Medium,0.07,4.13,0.50,48,Geoffrey Hewitt,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Springfield,62701,2012-08-13,2012-08-16,60.80970,22,88.13,87713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9407,23074,Low,0.01,155.99,8.99,3398,Marc McDaniel,Regular Air,Corporate,Technology,...,Central,Illinois,Decatur,62521,2011-11-22,2011-11-22,82.66500,5,689.14,87539
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,...,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.42600,41,7158.10,87544
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.91230,29,1705.67,87551
9411,26074,Critical,0.05,4.13,0.50,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,117.26550,40,169.95,87551
9412,26075,Critical,0.01,30.98,17.08,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,3.90688,11,373.27,87551

In [61]:
#7.display orders where Ship Mode=Regular Air and Sales>200.
data[(data["Ship Mode"]=="Regular Air")&(data["Sales"]>200)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.46730,16,1515.17,90194
12,24565,Critical,0.10,85.99,0.99,6,Dwight Hwang,Regular Air,Home Office,Technology,...,West,California,San Jose,95123,2012-12-29,2012-12-31,1176.50520,24,1705.08,90200
13,21866,High,0.05,12.28,4.86,7,Leon Gill,Regular Air,Home Office,Office Supplies,...,East,Massachusetts,Fall River,2724,2012-10-30,2012-10-31,72.99280,19,232.95,90198
16,22241,Critical,0.06,15.57,1.39,10,Meredith Norris Thomas,Regular Air,Home Office,Office Supplies,...,East,New Jersey,Pennsauken,8109,2011-10-04,2011-10-05,142.79550,14,206.95,90195
17,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,2010-08-15,2010-08-17,-53.80960,22,211.15,90192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.91230,29,1705.67,87551
9412,26075,Critical,0.01,30.98,17.08,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,3.90688,11,373.27,87551
9417,23413,Critical,0.07,115.79,1.99,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2013-04-27,2013-04-29,606.30990,8,878.71,87546
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,...,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.48150,19,596.35,87549
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.86000,13,447.87,87532

In [62]:
# OR(|)
#1.display records where Region=East or Region=West.
data[(data["Region"]=="East")|(data["Region"]=="West")]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [63]:
#2.dispaly products where Product Category=Furniture or Technology.
data[(data["Product Category"]=="Furniture")|(data["Product Category"]=="Technology")]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
12,24565,Critical,0.10,85.99,0.99,6,Dwight Hwang,Regular Air,Home Office,Technology,...,West,California,San Jose,95123,2012-12-29,2012-12-31,1176.505200,24,1705.08,90200
14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,...,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9417,23413,Critical,0.07,115.79,1.99,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2013-04-27,2013-04-29,606.309900,8,878.71,87546
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,...,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.481500,19,596.35,87549
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

In [65]:
#3.Display records where Sales>1000 or Profit>500.
data[(data["Sales"]>1000)|(data["Profit"]>500)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.467300,16,1515.17,90194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,...,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.426000,41,7158.10,87544
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.912300,29,1705.67,87551
9417,23413,Critical,0.07,115.79,1.99,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2013-04-27,2013-04-29,606.309900,8,878.71,87546
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533

In [66]:
#4.display orders where discount>0.10 or Shipping Cost>30.
data[(data["Discount"]>0.10)|(data["Shipping Cost"]>30)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,...,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
15,20877,Medium,0.10,286.85,61.76,9,Lorraine Houston,Delivery Truck,Home Office,Furniture,...,East,New Jersey,Camden,8101,2012-12-25,2012-12-27,-346.615198,8,1794.27,90199
42,25082,Not Specified,0.06,64.65,35.00,20,Marion Nolan Kaplan,Express Air,Small Business,Office Supplies,...,Central,Nebraska,Bellevue,68005,2012-05-31,2012-06-02,-929.680000,13,802.21,90036
53,7082,Not Specified,0.06,64.65,35.00,21,Tony Wilkins Winters,Express Air,Small Business,Office Supplies,...,East,New York,New York City,10012,2012-05-31,2012-06-02,-929.680000,50,3085.41,50533
60,18478,Low,0.10,146.05,80.20,23,Lynn Moss,Delivery Truck,Corporate,Furniture,...,West,California,Laguna Hills,92653,2013-11-18,2013-11-25,353.772160,11,1591.71,87669
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9378,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533,2010-11-11,2010-11-12,67.012000,9,894.64,90154
9394,19370,High,0.00,140.98,53.48,3396,Stuart Wiley,Delivery Truck,Corporate,Furniture,...,Central,Illinois,Crystal Lake,60014,2012-08-16,2012-08-17,-140.727600,16,2327.54,87542
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,...,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.426000,41,7158.10,87544
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533

In [67]:
#5.display customers from California or Texas.
data[(data["State or Province"]=="California")|(data["State or Province"]=="Texas")]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.36650,12,6362.85,90193
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.26000,18,113.25,90197
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.46730,16,1515.17,90194
10,24563,Critical,0.07,6.48,6.60,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,-13.86000,4,28.61,90200
11,24564,Critical,0.01,4.84,0.71,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,...,West,California,San Jose,95123,2012-12-29,2012-12-31,57.58050,17,83.45,90200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9267,24781,Critical,0.03,7.64,1.39,3355,Glenda Simon,Regular Air,Corporate,Office Supplies,...,West,California,Camarillo,93010,2013-04-09,2013-04-10,65.28780,12,94.62,88596
9268,22916,Not Specified,0.01,46.89,5.10,3355,Glenda Simon,Regular Air,Corporate,Office Supplies,...,West,California,Camarillo,93010,2013-08-02,2013-08-04,193.94520,6,281.08,88597
9378,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533,2010-11-11,2010-11-12,67.01200,9,894.64,90154
9379,19774,Low,0.00,3.28,0.98,3388,Aaron Shaffer,Express Air,Corporate,Office Supplies,...,West,California,Fairfield,94533,2011-01-07,2011-01-12,26.35680,11,39.85,90155
9380,22719,High,0.04,5.40,7.78,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533,2012-08-18,2012-08-20,-29.27808,5,29.81,90157

In [68]:
#6.dispaly orders where ship Mode=Express Air or Dilivery Truck.
data[(data["Ship Mode"]=="Express Air")|(data["Ship Mode"]=="Delivery Truck")]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9413,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554,2010-10-04,2010-10-04,-24.710400,15,135.78,87537
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [69]:
#7. display records where Profit<0 or Sales>2000.
data[(data["Profit"]<0)|(data["Sales"]>2000)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,...,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.260000,18,113.25,90197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9415,26043,Not Specified,0.06,30.98,6.50,3400,Florence Gold,Regular Air,Corporate,Technology,...,East,West Virginia,Fairmont,26554,2012-07-04,2012-07-07,-113.600000,3,96.79,87540
9418,23414,Critical,0.02,37.44,4.27,3400,Florence Gold,Regular Air,Corporate,Office Supplies,...,East,West Virginia,Fairmont,26554,2013-04-27,2013-04-30,-15.030000,1,43.90,87546
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533